/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class merrg1n_jajaime_IMEManager */

#ifndef _Included_merrg1n_jajaime_IMEManager
#define _Included_merrg1n_jajaime_IMEManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     merrg1n_jajaime_IMEManager
 * Method:    getHWND
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_merrg1n_jajaime_IMEManager_getHWND
  (JNIEnv *, jclass, jstring);

/*
 * Class:     merrg1n_jajaime_IMEManager
 * Method:    associateContext
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_merrg1n_jajaime_IMEManager_associateContext
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
